name: Style

on:
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      # setup the repository
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5


      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - run: |
          uv venv
          uv pip compile --extra=dev pyproject.toml -o requirements.txt
          uv pip sync requirements.txt

      - run: echo "$PWD/.venv/bin" >> $GITHUB_PATH

      # linting
      - uses: astral-sh/ruff-action@v1

      # type checking
      - uses: jakebailey/pyright-action@v2
        with:
          pylance-version: latest-release
